from .common import RAW_DATA_DIR, PROCESSED_DATA_DIR

RAW_DATA_DIR = RAW_DATA_DIR / "3D-FRONT" / "3D-FRONT-TEST-SCENE"
PROCESSED_DATA_DIR = PROCESSED_DATA_DIR / "3D-FRONT" / "3D-FRONT-TEST-SCENE"
RENDERS_DATA_DIR = PROCESSED_DATA_DIR / "renders"
